apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world-app
  name: hello-world-app-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hello-world-app
  type: NodePort
