apiVersion: v1
kind: Pod
metadata:
  name: hello-world-app-pod
  labels:
    app: hello-world-app
spec:
  containers:
    - name: hello-world-app
      image: sdubey321/hello-world-app:v1.0.0
      ports:
        - containerPort: 80
